package net.zomis.cards.cwars2.ais;

import net.zomis.cards.cwars2.CWars2CardFactory;
import net.zomis.cards.cwars2.CWars2Res;
import net.zomis.cards.util.DeckList;

public class CWars2Decks {
	public static DeckList cheat(DeckList deck) {
		return DeckList.newInstance("CHEAT " + deck).add(deck).add(5, "CHEAT");
	}
	public static DeckList zomisSingleplayerControl() {
		return DeckList.newInstance("SP Control")
				.add(1, "Archer")
				.add(3, "Cannon")
				.add(2, "Ambush")
				.add(5, "Thief16")
				.add(4, "Recruit")
				.add(5, "Guards")
				.add(4, "Mage")
				.add(1, "Lightning")
				.add(1, "Quake")
				.add(2, "Pixies")
				.add(5, "Add Weapons")
				.add(4, "Add Bricks")
				.add(2, "Remove Weapons")
				.add(2, "Remove Crystals")
				.add(2, "Remove Bricks")
				.add(4, "Builder")
				.add(5, "Tavern")
				.add(1, "Babylon")
				.add(2, "School")
				.add(3, "Wain")
				.add(1, "All Bricks")
				.add(2, "Large Wall")
				.add(3, "SuperSacrifice Builders")
				.add(3, "SuperSacrifice Wizards")
				.add(2, "SuperSacrifice Recruits")
				.add(1, "Dragon")
				.add(1, "Trojan Horse")
				.add(1, "Comet Strike")
				.add(3, "Curse");
	}
	public static DeckList zomisSingleplayerComputer() {
		return DeckList.newInstance("SP Computer")
				.add("4 Bomb")
				.add("3 Cannon")
				.add("2 Platoon")
				.add("2 Ambush")
				.add("5 Thief16")
				.add("4 Recruit")
				.add("4 Guards")
				.add("4 Mage")
				.add("2 Lightning")
				.add("3 Pixies")
				.add("1 Magic Wall")
				.add("5 Add Weapons")
				.add("3 Add Bricks")
				.add("1 Remove Crystals")
				.add("1 All Crystals")
				.add("4 Builder")
				.add("2 Tower")
				.add("5 Tavern")
				.add("1 Babylon")
				.add("1 School")
				.add("3 Catapult")
				.add("2 Battering Ram")
				.add("4 Wain")
				.add("2 Large Wall")
				.add("1 Dragon")
				.add("1 Trojan Horse")
				.add("1 Comet Strike")
				.add("4 Curse");
	}
	public static DeckList zomisSingleplayerMyLocalDeck() {
		return DeckList.newInstance("SP MyLocalDeck")
				.add("1 Archer")
				.add("3 Bomb")
				.add("3 Cannon")
				.add("1 Platoon")
				.add("1 Ambush")
				.add("5 Thief16")
				.add("5 Recruit")
				.add("4 Guards")
				.add("5 Mage")
				.add("1 Lightning")
				.add("1 Quake")
				.add("3 Pixies")
				.add("1 Magic Wall")
				.add("5 Add Weapons")
				.add("3 Add Bricks")
				.add("2 Remove Weapons")
				.add("1 Remove Crystals")
				.add("1 Remove Bricks")
				.add("5 Builder")
				.add("5 Tavern")
				.add("1 Babylon")
				.add("1 School")
				.add("5 Catapult")
				.add("3 Battering Ram")
				.add("3 Wain")
				.add("1 Large Wall")
				.add("1 SuperSacrifice Builders")
				.add("1 SuperSacrifice Wizards")
				.add("1 SuperSacrifice Recruits")
				.add("1 Dragon")
				.add("1 Comet Strike");
	}
	public static DeckList zomisSingleplayerBuilding() {
		return DeckList.newInstance("SP Building")
				.add("1 Archer")
				.add("3 Cannon")
				.add("5 Thief16")
				.add("3 Recruit")
				.add("5 Guards")
				.add("5 Mage")
				.add("5 Pixies")
				.add("3 Magic Wall")
				.add("2 Magic Defense")
				.add("5 Add Weapons")
				.add("5 Add Bricks")
				.add("2 Remove Weapons")
				.add("2 Remove Crystals")
				.add("2 All Crystals")
				.add("5 Builder")
				.add("4 Tower")
				.add("5 Tavern")
				.add("2 Babylon")
				.add("1 School")
				.add("2 All Bricks")
				.add("2 Large Wall")
				.add("5 Reverse")
				.add("1 Trojan Horse");
	}
	public static DeckList zomisSingleplayerDefaultWithoutSpyAndSabotage98cards() {
		return DeckList.newInstance("SP Default No_Spy_and_Sabotage")
				.add("2 Archer")
				.add("2 Fire Archer")
				.add("3 Bomb")
				.add("3 Cannon")
				//		.add("1 Spy")
				.add("3 Platoon")
				.add("2 Ambush")
				.add("3 Knight")
				.add("2 Thief16")
				.add("4 Recruit")
				.add("2 Guards")
				.add("1 Roadblock")
				.add("1 All Weapons")
				//		.add("2 Sabotage")
				.add("4 Mage")
				.add("2 Lightning")
				.add("2 Quake")
				.add("3 Pixies")
				.add("1 Magic Wall")
				.add("2 Magic Defense")
				.add("2 Magic Weapons")
				.add("3 Add Weapons")
				.add("3 Add Crystals")
				.add("3 Add Bricks")
				.add("2 Remove Weapons")
				.add("2 Remove Crystals")
				.add("2 Remove Bricks")
				.add("1 All Crystals")
				.add("4 Builder")
				.add("5 Tower")
				.add("1 Tavern")
				.add("2 House")
				.add("3 Babylon")
				.add("4 Wall")
				.add("2 School")
				.add("2 Fence")
				.add("3 Catapult")
				.add("2 Battering Ram")
				.add("3 Wain")
				.add("1 All Bricks")
				.add("4 Large Wall")
				.add("2 Reverse");
	}

	public static DeckList zomisMultiplayerBuildingDeck() {
		return DeckList.newInstance("Building")
				.add(2, "Bomb")
				.add(2, "Cannon")
				.add(5, "Thief")
				.add(3, "Recruit")
				.add(5, "Guards")
				.add(5, "Mage")
				.add(4, "Pixies")
				.add(2, "Magic Wall")
				.add(3, "Add Bricks") 
				.add(4, "Remove Weapons")
				.add(4, "Remove Crystals")
				.add(3, "Remove Bricks")
				.add(5, "Builder")
				.add(5, "Tavern")
				.add(3, "Babylon")
				.add(1, "School")
				.add(4, "Large Wall")
				.add(3, "Reverse")
				.add(4, "Hail Storm")
				.add(4, "Ram Attack")
				.add(4, "Giant Snowball");
	}
	
	public static DeckList zomisMultiplayerDeck() {
		return DeckList.newInstance("Agressive")
		.add(1, "Archer")
		.add(4, "Bomb")
		.add(3, "Cannon")
		.add(5, "Thief")
		.add(4, "Recruit")
		.add(2, "Guards")
		
		.add(5, "Mage")
		.add(1, "Quake")
		.add(1, "Pixies")
		.add(1, "Magic Wall")
		
		.add(5, "Add Weapons")
		.add(5, "Add Bricks")
		.add(2, "Remove Weapons")
		.add(2, "Remove Crystals")
		.add(2, "Remove Bricks")
		
		.add(4, "Builder")
		.add(5, "Tavern")
		.add(2, "Catapult")
		.add(4, "Wain")
		.add(1, "Trojan Horse")
		
		.add(3, "Reward Workers")
		.add(1, "Remove Resources")
		.add(4, "Hail Storm")
		.add(5, "Giant Snowball")
		.add(5, "Ram Attack");
	}
	
	public static DeckList crapDeck() {
		return DeckList.newInstance("Crap")
			.add(5, "Archer")
			.add(5, "Fire Archer")
			.add(5, "Roadblock")
			.add(5, "All Weapons")
			.add(5, "Magic Defense")
			.add(5, "Magic Weapons")
			.add(5, "All Crystals")
			.add(5, "Babylon")
			.add(5, "Wall")
			.add(5, "School")
			.add(5, "Sacrifice Builders")
			.add(5, "Sacrifice Recruits")
			.add(5, "Sacrifice Wizards")
			.add(5, "Dragon")
			.add(5, "Trojan Horse");
	}
	public static CWars2CardFactory cardCheat() {
		return new CWars2CardFactory("CHEAT").setMyEffect(CWars2Res.CASTLE, 200).setDamage(200).setCastleDamage(200);
	}
	
}
